---
title: "State Time Series Analysis"
author: "James Monks"
date: "14/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(fable)
fires_clean <- read_rds(here::here("data", "fires_clean.rds"))
```

# Breaking the Data Up
The data will be broken up into individual time series.
```{r}
state_list <- fires_clean %>% 
  as_tibble() %>% 
  group_by(state) %>% 
  group_split() %>% 
  map(as_tsibble, index = date)
```

# Modelling and Forecasting Each State
The same models that were trained for the aggregate time series can be trained for all of the states.

```{r}
state_models <- state_list %>% 
  map(~{
    .x %>% 
      model(
        arima = ARIMA(fires),
        snaive = SNAIVE(fires)
      )
  })

```



```{r warning=FALSE}
state_forecasts <- state_models %>% 
  map(forecast, h = "2 years")
```


# Visualising
Creating visualisations for each of the 

```{r warning=FALSE}
plot_list <- map2(state_forecasts, state_list, ~{
  .x %>% 
    autoplot(filter(.y, date > lubridate::ymd("2012-01-01")))
})
```

```{r warning=FALSE}
library(patchwork)

wrap_plots(plot_list, ncol = 4)
```




